### ISSUE TITLE
Cluster producer doesn't compute time correctly

### ISSUE THREAD

**Issue by awhitbeck** [LDMX-Software/TrigScint#14]
With the new QIEDigiProducer, clustering computes times incorrectly.  The hit time is not always measured; for low-amplitude pulses, the TDC won't fire and a time won't be recorded.  In the RecHit producer, the time reported is -1 and this gets included in the average time of hits included in clusters.  

Proposal: Changes RecHitProducuer to set rechit times to -999 when TDC doesn't fire.  Add a check to the cluster producer so that it skips these RecHits.  This will mean that it computes cluster times in the same manner as before for the old digi pipeline and the new digi pipeline.

**Comment by bryngemark** [comment]
Maybe this is a stupid question, but, if the TDC isn't fired, why are we keeping these hits? For performance studies?

**Comment by awhitbeck** [comment]
Depending on how you set the TDC threshold, you can have a fairly large
pulse, maybe 20% of a MIP, that wouldn't fire the TDC.  This is much higher
than the expected noise, so there is likely useful information there to
take advantage of.   You can also have situations where the TDC is still
latched from a previous time sample, this would happen if, for example, a
very large pulse occurred.  In general, the clustering should be agnostic
to configurations of the digi code (or eventually the detector) as much as
possible.

This touches on zero-suppression to some extent.  Currently, we haven't
decided if or how we would do zero suppression.  It would almost certainly
be done in the TDAQ system, so I think it should be in the list of
questions that we think about for triggering.  However, this system is so
small that even if we did have a zero suppression, I would not use the TDC
as the decision variable, but just remove all hits consistent with noise.
You can always ignore hits that don't fire the TDC in online or offline
reconstruction.

I should say that we did implement a very rudimentary zero suppression into
the digi code that can be tweaked.  However, if we're not going to zero
suppress data in the frontend, we should leave this for other producers
that are simulating the trigger and DAQ data to implement. Just my opinion,
though.

**Comment by awhitbeck** [comment]
okay, this is a simple fix.   Code in on [iss14](https://github.com/LDMX-Software/TrigScint/tree/iss14).

**Comment by awhitbeck** [comment]
If no one has an objection to this, I am going to merge it into trunk.  I have tested the code and it fixes things.  Its a necessary fix from timing studies, too. 

Once this is merged, I would l like to update the ldmx-sw PR to get this merged there.

**Comment by bryngemark** [comment]
I don't have ay objections. It struck me though, is there anywhere there will be problem setting the hit time to a negative number? I assume TDC is an unsigned integer. (Also if we find such a case we can easily fix it.)

**Comment by awhitbeck** [comment]
The TDC is an unsigned integer, but it can be fired in any one of N time samples.  So, if we decide that the leading edge of the sample of interest is zero,  then you actually can get negative times relative to that.

**Comment by bryngemark** [comment]
Gotcha
