### ISSUE TITLE
Time-Based Seeding

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/TrigScint#20]
Hi TS devs!

I've been running large-scale comparisons to validate my own developments, and I've noticed a (small) issue that should hopefully be easy to rectify. In your digi-producer, you use your own random seed provided from the python.

https://github.com/LDMX-Software/TrigScint/blob/8662abfeac25509b39e9ab604e14f686e852dac5/src/TrigScint/TrigScintDigiProducer.cxx#L28-L29

https://github.com/LDMX-Software/TrigScint/blob/5b210429691b1b91c5c77bdacad85ccc980a1e90/python/trigScint.py#L30-L31

While this time-based seeding is a reasonable default, we would like seeds for _alll_ steps in ldmx-sw to come from the centralized "Random Number Seed Service". This allows us to re-run the same process and produce the exact same output relatively easily without having to go poking for how to set all the different seeds. You can see an example on how I've used the RNSS in the ecal digi pipeline here: https://github.com/LDMX-Software/Ecal/blob/9c659df62ea7ee1327688e9350446f304f1a6e67/src/Ecal/EcalDigiProducer.cxx#L63-L64

Again, not a huge issue, but wanted to put it on your To-Do list.

**P.S.** I vaguely remember talking about this with @bryngemark in the past. Maybe the fix for this is on some branch somewhere? Or got lost in our rush to merge developments?

**Comment by bryngemark** [comment]
Hi Tom, I think this was discussed in the PR for the TS digi. The digi code already uses the RNSS but there was some reason why this was kept in one place. @GNiramay can probably comment.

**Comment by GNiramay** [comment]
Hi both,

At the moment, the `TrigScintDigiProducer` is just kept for sanity checks. The actual digitization is done by `TrigScintQIEDigiProducer` which uses the random seed service for all the randomization. So for all practical purposes, one should use `TrigScintQIEDigiProducer` and not `TrigScintDigiProducer`. Also, be aware that the output of `TrigScintQIEDigiProducer` is very different from that of `TrigScintDigiProducer`. For any kind of analysis, you would use `TrigScintRechitProducer` on the top of `TrigScintQIEDigiProducer` to get an output similar to `TrigScintDIgiProducer`,

 The issue you raised is valid and I think I can  make the changes in my upcoming PR
(Branch: https://github.com/LDMX-Software/TrigScint/tree/Energy_Reconstruction)

**Comment by bryngemark** [comment]
Thanks @GNiramay! I knew it would help to loop you in, I completely missed that this was about the old not-actual-digi producer 😄 

If you don't mind fixing this, that would be great. It's legacy code to some extent, but as you mention, not fully retired yet.

**Comment by GNiramay** [comment]
@bryngemark, Thanks for getting me into the loop and you are correct. Unless and until we are happy with the full reco chain, we would want to use the old digi producer as a baseline.

**Comment by GNiramay** [comment]
I have modified the code on my branch. If it is ok, it will appear in the trunk when I create a PR for this branch.

https://github.com/LDMX-Software/TrigScint/commit/19508cdfa7286b2df906217ec4cecd442cfb17b6
