### ISSUE TITLE
make digi producer less verbose 

### ISSUE THREAD

**Issue by bryngemark** [LDMX-Software/TrigScint#21]
I suggest the printout level here gets reduced from `info` to `debug` since it happens on (every sim) hit level rather then a few-events level or at the start/end of process, or similar.

alternatively, add an extra qualifier using the producer's own `verbose` parameter.

https://github.com/LDMX-Software/TrigScint/blob/5b210429691b1b91c5c77bdacad85ccc980a1e90/src/TrigScint/TrigScintQIEDigiProducer.cxx#L97

**Comment by bryngemark** [comment]
@GNiramay I just assigned this to you to make you aware, not as an order at all 😄   
whoever gets to it first will do it.

**Comment by GNiramay** [comment]
@bryngemark Thanks a lot. Honestly, I am not well versed with `ldmx_log()` method. My idea behind using `ldmx_log(info)` was just to make sure the verbosity is handled properly. Please feel free to change it to `debug`. In fact, I had done a lousy job in printing out the debug info.
