### ISSUE TITLE
seed for random numbers not set correctly

### ISSUE THREAD

**Issue by awhitbeck** [LDMX-Software/TrigScint#3]
There are currently two places where `TrigScintDigiProducer` generates random numbers: 

1. the `random_` variable that is used to generate random IDs and randomizes the response of the SiPM
2. the `noiseGenerator_` object that simulates the number of 'pure' noise hits

`random_` seems to not have its seeds set from the conditions database.  We should handle this consistently. 

For `noiseGenerator_` this is passes a string "TrigScintDigiProducer::NoiseGenerator".  However, our nominal workflow is duplicated for each of the three arrays.  This string should make use of `outputCollection_` so that each producer get a different set of random numbers.

**Comment by tomeichlersmith** [comment]
Just popping in to this repo becuase I helped Jeremy code up the RNSS. The RNSS is configured at the beginning of the run, so it is safest to use it in `produce`. The following is untested, but should get you close:
```
  // Need to handle seeding on the first event
  if (random_.get() == nullptr) {
	const auto& rseed = getCondition<RandomNumberSeedService>(RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
	random_ = std::make_unique<TRandom3>(rseed.getSeed("TrigScintDigiProducer::random"));
  }
```
For this to work, you will need to remove the construction of `random_` in the constructor.

**Comment by awhitbeck** [comment]
omg, you're amazing.  We're trying to implement this in @GNiramay branch and the code is throwing a weird exception and I am quite sure this is why!

**Comment by awhitbeck** [comment]
I think this is resolve in recent commits.  Please reopen, if not.
